# Generated by Django 4.2.11 on 2024-03-15 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PEN', '대기'), ('COM', '완료'), ('CAN', '취소'), ('FAL', '실패')], default='PEN', max_length=10)),
                ('price', models.PositiveIntegerField()),
                ('buyer_uuid', models.UUIDField()),
                ('seller_uuid', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PEN', '대기'), ('COM', '완료'), ('CAN', '취소'), ('FAL', '실패')], default='PEN', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.payment')),
            ],
        ),
    ]
