# Generated by Django 4.2.4 on 2023-11-06 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0002_points_used_point_alter_points_point_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='points',
            options={'ordering': ['-created_at'], 'verbose_name': 'points', 'verbose_name_plural': 'points'},
        ),
        migrations.RenameField(
            model_name='points',
            old_name='point',
            new_name='points',
        ),
    ]
