# Generated by Django 4.2.4 on 2023-11-06 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0003_alter_points_options_rename_point_points_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='points',
            old_name='used_point',
            new_name='used_points',
        ),
    ]
