# Generated by Django 4.2.9 on 2024-01-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0004_rename_used_point_points_used_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='points',
            name='description',
            field=models.CharField(db_comment='포인트 설명', default='', max_length=100),
        ),
        migrations.AddField(
            model_name='points',
            name='title',
            field=models.CharField(db_comment='포인트 제목', default='', max_length=20),
        ),
    ]
