# Generated by Django 4.2.9 on 2024-01-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0005_pointsuse_points_description_points_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='description',
            field=models.CharField(db_comment='포인트 설명', max_length=100),
        ),
        migrations.AlterField(
            model_name='points',
            name='title',
            field=models.CharField(db_comment='포인트 제목', max_length=20),
        ),
    ]
