# Generated by Django 4.2.9 on 2024-01-11 00:07

from django.conf import settings
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('point', '0006_alter_points_description_alter_points_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='points',
            name='user',
        ),
        migrations.DeleteModel(
            name='PointsUse',
        ),
        migrations.DeleteModel(
            name='Points',
        ),
    ]
