# Generated by Django 4.2.9 on 2024-01-11 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0007_pointsearndetails_pointsusedetails_userpoints_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsEarnDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_comment='포인트 적립 제목', max_length=20)),
                ('description', models.CharField(db_comment='포인트 적립 설명', max_length=100)),
                ('points', models.IntegerField(db_comment='적립 포인트', default=0)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_points_earn', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'points earn details',
                'verbose_name_plural': 'points earn details',
                'db_table': 'points_earn_details',
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='PointsUseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_comment='포인트 사용 제목', max_length=20)),
                ('description', models.CharField(db_comment='포인트 사용 설명', max_length=100)),
                ('points', models.IntegerField(db_comment='사용 포인트', default=0)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_points_use', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'points use details',
                'verbose_name_plural': 'points use details',
                'db_table': 'points_use_details',
                'ordering': ['-used_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(db_comment='적립 포인트', default=0)),
                ('used_points', models.IntegerField(db_comment='사용 포인트', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', '사용 가능'), ('PARTIAL', '부분 사용'), ('USED', '사용 완료'), ('EXPIRED', '기한 만료')], default='ACTIVE', max_length=10)),
                ('valid_until', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'points',
                'verbose_name_plural': 'points',
                'db_table': 'points',
                'ordering': ['-created_at'],
            },
        ),

    ]
