# Generated by Django 4.2.9 on 2024-03-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0009_pointsearndetails_valid_days_alter_userpoints_points_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointsearndetails',
            options={'ordering': ['-earned_at']},
        ),
        migrations.AlterModelOptions(
            name='pointsusedetails',
            options={'ordering': ['-used_at']},
        ),
        migrations.AlterModelOptions(
            name='userpoints',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='pointsearndetails',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pointsearndetails',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pointsearndetails',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pointsearndetails',
            name='valid_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pointsusedetails',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pointsusedetails',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pointsusedetails',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userpoints',
            name='points',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userpoints',
            name='used_points',
            field=models.IntegerField(default=0),
        ),
    ]
