# Generated by Django 4.2.8 on 2024-03-08 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('commenter_uuid', models.UUIDField(editable=False)),
                ('content', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='post.post')),
            ],
            options={
                'db_table': 'comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('commenter_uuid', models.UUIDField(editable=False)),
                ('content', models.TextField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recomments', to='comment.comment')),
            ],
            options={
                'db_table': 'recomment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReCommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('report_user_uuid', models.UUIDField(editable=False)),
                ('report_content', models.TextField()),
                ('report_reason', models.CharField(choices=[('AD', '광고'), ('SP', '스팸'), ('AV', '성인물'), ('VI', '폭력적인 내용'), ('IL', '불법적인 내용'), ('OT', '기타')], default='OT', max_length=2)),
                ('reviewed', models.BooleanField(default=False)),
                ('feedback', models.TextField(null=True)),
                ('recomment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comment.recomment')),
            ],
            options={
                'db_table': 'recomment_report',
            },
        ),
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('report_user_uuid', models.UUIDField(editable=False)),
                ('report_content', models.TextField()),
                ('report_reason', models.CharField(choices=[('AD', '광고'), ('SP', '스팸'), ('AV', '성인물'), ('VI', '폭력적인 내용'), ('IL', '불법적인 내용'), ('OT', '기타')], default='OT', max_length=2)),
                ('reviewed', models.BooleanField(default=False)),
                ('feedback', models.TextField(null=True)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comment.comment')),
            ],
            options={
                'db_table': 'comment_report',
            },
        ),
        migrations.CreateModel(
            name='ReCommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uuid', models.UUIDField(editable=False)),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('recomment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.recomment')),
            ],
            options={
                'db_table': 'recomment_like',
                'unique_together': {('recomment', 'user_uuid')},
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uuid', models.UUIDField(editable=False)),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.comment')),
            ],
            options={
                'db_table': 'comment_like',
                'unique_together': {('comment', 'user_uuid')},
            },
        ),
    ]
