# Generated by Django 4.2.11 on 2024-03-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commenter_uuid',
            field=models.UUIDField(),
        ),
    ]
