# Generated by Django 4.2.11 on 2024-03-26 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_alter_commentlike_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReCommentDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uuid', models.UUIDField(editable=False)),
                ('disliked_at', models.DateTimeField(auto_now_add=True)),
                ('recomment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.recomment')),
            ],
            options={
                'db_table': 'recomment_dislike',
                'unique_together': {('recomment', 'user_uuid')},
            },
        ),
        migrations.CreateModel(
            name='CommentDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uuid', models.UUIDField(editable=False)),
                ('disliked_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_dislikes', to='comment.comment')),
            ],
            options={
                'db_table': 'comment_dislike',
                'unique_together': {('comment', 'user_uuid')},
            },
        ),
    ]
