# Generated by Django 4.2.11 on 2024-03-27 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_recommentdislike_commentdislike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreport',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_reports', to='comment.comment'),
        ),
        migrations.AlterField(
            model_name='recommentreport',
            name='recomment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomment_reports', to='comment.recomment'),
        ),
    ]
