# Generated by Django 4.2.11 on 2024-03-27 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_alter_commentreport_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreport',
            name='reviewed',
        ),
        migrations.RemoveField(
            model_name='recommentreport',
            name='reviewed',
        ),
        migrations.AddField(
            model_name='commentreport',
            name='report_status',
            field=models.IntegerField(choices=[(0, '대기중'), (1, '수락됨'), (2, '거부됨'), (3, '일부 수락됨')], default=0),
        ),
        migrations.AddField(
            model_name='commentreport',
            name='review_status',
            field=models.IntegerField(choices=[(0, '제출됨'), (1, '검토중'), (2, '검토 완료')], default=0),
        ),
        migrations.AddField(
            model_name='recommentreport',
            name='report_status',
            field=models.IntegerField(choices=[(0, '대기중'), (1, '수락됨'), (2, '거부됨'), (3, '일부 수락됨')], default=0),
        ),
        migrations.AddField(
            model_name='recommentreport',
            name='review_status',
            field=models.IntegerField(choices=[(0, '제출됨'), (1, '검토중'), (2, '검토 완료')], default=0),
        ),
    ]
