# Generated by Django 4.2.4 on 2023-11-04 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_name', models.CharField(max_length=100)),
                ('coupon_description', models.CharField(max_length=100)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('valid_days', models.IntegerField()),
            ],
            options={
                'verbose_name': 'coupon_type',
                'verbose_name_plural': 'coupon_types',
                'db_table': 'coupon_type',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', '사용 가능'), ('USED', '사용 완료'), ('EXPIRED', '쿠폰 만료')], default='ACTIVE', max_length=10)),
                ('valid_until', models.DateTimeField(null=True)),
                ('coupon_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_type', to='coupon.coupontype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'coupon',
                'verbose_name_plural': 'coupons',
                'db_table': 'coupon',
            },
        ),
    ]
