# Generated by Django 4.2.8 on 2024-01-04 05:40

import coupon.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponClass',
            fields=[
                ('code', models.CharField(default=coupon.models.CouponClass.coupon_code_generator, editable=False, max_length=19, primary_key=True, serialize=False)),
                ('coupon_name', models.CharField(max_length=100)),
                ('coupon_description', models.CharField(max_length=100)),
                ('coupon_issuer_type', models.CharField(choices=[('CAT', '캐치비'), ('FAC', '시설'), ('COA', '코치'), ('NUL', '없음')], default='NUL', max_length=3)),
                ('issue_valid_days', models.IntegerField()),
                ('use_valid_days', models.IntegerField()),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('max_count', models.IntegerField()),
                ('current_count', models.IntegerField(default=0)),
                ('coupon_type', models.CharField(choices=[('PCNT', '할인율'), ('AMNT', '금액'), ('FREE', '무료')], default='PCNT', max_length=4)),
                ('discount_value', models.IntegerField()),
                ('coupon_issuer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_issuer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'coupon class',
                'verbose_name_plural': 'coupon classes',
                'db_table': 'coupon_class',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACT', '사용 가능'), ('USE', '사용 완료'), ('EXP', '기한 만료')], default='ACT', max_length=3)),
                ('valid_until', models.DateTimeField(null=True)),
                ('used_at', models.DateTimeField(null=True)),
                ('coupon_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_class', to='coupon.couponclass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'coupon',
                'verbose_name_plural': 'coupons',
                'db_table': 'coupon',
                'unique_together': {('user', 'coupon_class')},
            },
        ),
    ]
