# Generated by Django 4.2.4 on 2023-11-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('coupon_id', models.AutoField(primary_key=True, serialize=False)),
                ('coupon_name', models.CharField(max_length=100)),
                ('coupon_description', models.CharField(max_length=100)),
                ('coupon_code', models.CharField(max_length=100)),
                ('coupon_discount', models.FloatField()),
                ('coupon_start_date', models.DateTimeField()),
                ('coupon_end_date', models.DateTimeField()),
                ('coupon_created_date', models.DateTimeField(auto_now_add=True)),
                ('coupon_updated_date', models.DateTimeField(auto_now=True)),
                ('coupon_is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
