# Generated by Django 4.2.9 on 2024-01-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponclass',
            name='multiple_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='issued_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='used_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
