# Generated by Django 4.2.4 on 2023-12-28 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_rename_coupontype_couponclass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(choices=[('PERCENTAGE', '비율 할인'), ('AMOUNT', '금액 할인')], default='PERCENTAGE', max_length=10),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='status',
            field=models.CharField(choices=[('ACTIVE', '사용 가능'), ('USED', '사용 완료'), ('EXPIRED', '기한 만료')], default='ACTIVE', max_length=10),
        ),
    ]
