# Generated by Django 4.2.9 on 2024-03-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_alter_couponclass_issue_valid_days_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={},
        ),
        migrations.AlterModelOptions(
            name='couponclass',
            options={},
        ),
        migrations.AlterField(
            model_name='couponclass',
            name='coupon_description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='couponclass',
            name='coupon_name',
            field=models.CharField(max_length=20),
        ),
    ]
