# Generated by Django 4.2.4 on 2023-11-15 10:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LessonProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_comment='상품명', max_length=100)),
                ('description', models.TextField(db_comment='상품 설명')),
                ('price', models.IntegerField(db_comment='가격')),
                ('main_coach', models.UUIDField(db_comment='코치 고유번호')),
                ('num_sessions', models.IntegerField(db_comment='세션 수')),
                ('num_finished', models.IntegerField(db_comment='완료된 세션 수', default=0)),
                ('num_booked', models.IntegerField(db_comment='예약된 세션 수', default=0)),
            ],
            options={
                'verbose_name': '레슨 상품',
                'verbose_name_plural': '레슨 상품',
                'db_table': 'lesson_product',
            },
        ),
        migrations.CreateModel(
            name='LessonSession',
            fields=[
                ('uuid', models.UUIDField(db_comment='세션 고유번호', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sub_coaches', models.JSONField(db_comment='보조 코치 고유번호 배열', null=True)),
                ('reserved_user', models.UUIDField(db_comment='사용자 고유번호')),
                ('start_datetime', models.DateTimeField(db_comment='시작 날짜/시간')),
                ('end_datetime', models.DateTimeField(db_comment='종료 날짜/시간')),
                ('status', models.CharField(choices=[('PE', '대기중'), ('CO', '예약승인됨'), ('CA', '취소됨'), ('FI', '완료됨')], db_comment='상태', default='PE', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='생성일')),
                ('confirmed_at', models.DateTimeField(blank=True, db_comment='승인일', null=True)),
                ('product', models.ForeignKey(db_comment='레슨 상품 고유번호', on_delete=django.db.models.deletion.DO_NOTHING, to='lesson.lessonproduct')),
            ],
            options={
                'verbose_name': '레슨',
                'verbose_name_plural': '레슨',
                'db_table': 'lesson',
            },
        ),
        migrations.CreateModel(
            name='LessonReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.UUIDField(db_comment='레슨 고유번호')),
                ('user', models.UUIDField(db_comment='사용자 고유번호')),
                ('content', models.TextField(db_comment='내용')),
                ('content_open', models.BooleanField(db_comment='내용 공개 여부', default=False)),
                ('images', models.JSONField(blank=True, db_comment='이미지 URL 배열', null=True)),
                ('stars', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], db_comment='별점')),
            ],
            options={
                'verbose_name': '레슨 리뷰',
                'verbose_name_plural': '레슨 리뷰',
                'db_table': 'lesson_review',
                'indexes': [models.Index(fields=['user'], name='lesson_review_user_index')],
            },
        ),
    ]
