# Generated by Django 4.2.4 on 2023-10-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='coach',
            new_name='main_coach',
        ),
        migrations.AddField(
            model_name='lesson',
            name='sub_coaches',
            field=models.JSONField(blank=True, db_comment='보조 코치 고유번호 배열', null=True),
        ),
        migrations.CreateModel(
            name='LessonReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.UUIDField(db_comment='레슨 고유번호')),
                ('user', models.UUIDField(db_comment='사용자 고유번호')),
                ('content', models.TextField(db_comment='내용')),
                ('images', models.JSONField(blank=True, db_comment='이미지 URL 배열', null=True)),
                ('stars', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], db_comment='별점')),
            ],
            options={
                'db_table': 'lesson_review',
                'indexes': [models.Index(fields=['user'], name='lesson_review_user_index')],
            },
        ),
    ]
