# Generated by Django 4.2.4 on 2023-10-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.UUIDField(db_comment='시설 고유번호')),
                ('user', models.UUIDField(db_comment='사용자 고유번호')),
                ('content', models.TextField(db_comment='내용')),
                ('images', models.JSONField(blank=True, db_comment='이미지 URL 배열', null=True)),
                ('stars', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], db_comment='별점')),
            ],
            options={
                'db_table': 'review',
                'indexes': [models.Index(fields=['facility'], name='facility_index'), models.Index(fields=['user'], name='user_index')],
            },
        ),
    ]
