# Generated by Django 4.2.11 on 2024-03-15 02:40

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=core.models.CustomAutoField(primary_key=True, serialize=False),
        ),
    ]
