# Generated by Django 4.2.11 on 2024-03-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_image_post_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tag',
            name='icon',
            field=models.URLField(),
        ),
    ]
