# Generated by Django 4.2.11 on 2024-03-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_postlike_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_under_review',
            field=models.BooleanField(default=False),
        ),
    ]
