# Generated by Django 4.2.11 on 2024-03-27 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_postdislike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreport',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_reports', to='post.post'),
        ),
    ]
