# Generated by Django 4.2.10 on 2024-03-18 02:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LessonProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('main_coach', models.UUIDField()),
                ('num_sessions', models.IntegerField()),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'lesson_product',
            },
        ),
        migrations.CreateModel(
            name='LessonPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_coaches', models.JSONField(null=True)),
                ('user', models.UUIDField()),
                ('num_finished', models.IntegerField(default=0)),
                ('num_booked', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lesson.lessonproduct')),
            ],
            options={
                'db_table': 'lesson_purchase',
            },
        ),
        migrations.CreateModel(
            name='LessonSession',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('PE', '대기'), ('CO', '확정'), ('CA', '취소'), ('FI', '완료')], default='PE', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lesson.lessonpurchase')),
            ],
            options={
                'db_table': 'lesson',
            },
        ),
    ]
