# Generated by Django 4.2.10 on 2024-02-29 05:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LessonProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_comment='상품명', max_length=100)),
                ('description', models.TextField(db_comment='상품 설명')),
                ('price', models.IntegerField(db_comment='가격')),
                ('main_coach', models.UUIDField(db_comment='코치 고유번호')),
                ('num_sessions', models.IntegerField(db_comment='세션 수')),
                ('deleted', models.BooleanField(db_comment='삭제 여부', default=False)),
            ],
            options={
                'verbose_name': '레슨 상품',
                'verbose_name_plural': '레슨 상품',
                'db_table': 'lesson_product',
            },
        ),
        migrations.CreateModel(
            name='LessonPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_coaches', models.JSONField(db_comment='보조 코치 고유번호 배열', null=True)),
                ('user', models.UUIDField(db_comment='사용자 고유번호')),
                ('num_finished', models.IntegerField(db_comment='완료된 세션 수', default=0)),
                ('num_booked', models.IntegerField(db_comment='예약된 세션 수', default=0)),
                ('product', models.ForeignKey(db_comment='레슨 상품 고유번호', on_delete=django.db.models.deletion.DO_NOTHING, to='lesson.lessonproduct')),
            ],
            options={
                'verbose_name': '레슨 구매',
                'verbose_name_plural': '레슨 구매',
                'db_table': 'lesson_purchase',
            },
        ),
        migrations.CreateModel(
            name='LessonSession',
            fields=[
                ('uuid', models.UUIDField(db_comment='세션 고유번호', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField(db_comment='시작 날짜/시간')),
                ('end_datetime', models.DateTimeField(db_comment='종료 날짜/시간')),
                ('status', models.CharField(choices=[('PE', '대기'), ('CO', '확정'), ('CA', '취소'), ('FI', '완료')], db_comment='상태', default='PE', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='생성일')),
                ('confirmed_at', models.DateTimeField(blank=True, db_comment='승인일', null=True)),
                ('purchase', models.ForeignKey(db_comment='레슨 구매 고유번호', on_delete=django.db.models.deletion.DO_NOTHING, to='lesson.lessonpurchase')),
            ],
            options={
                'verbose_name': '레슨',
                'verbose_name_plural': '레슨',
                'db_table': 'lesson',
            },
        ),
    ]
