# Generated by Django 4.2.4 on 2023-11-13 10:25

from django.db import migrations

from board.models import ForumCategory, Forum

def bulk_create_forums(apps, schema_editor):
    Forum.objects.bulk_create(
        objs=[
            Forum(
                forum_name="경기 매칭",
                category=ForumCategory.RECRUITMENT
            ),
            Forum(
                forum_name="용병 모집",
                category=ForumCategory.RECRUITMENT
            ),
            Forum(
                forum_name="팀원 모집",
                category=ForumCategory.RECRUITMENT
            ),
            Forum(
                forum_name="BC 모집",
                category=ForumCategory.RECRUITMENT
            ),
            Forum(
                forum_name="야구 정보",
                category=ForumCategory.INFORMATION
            ),
        ]
    )

def bulk_delete_forums(apps, schema_editor):
    Forum.objects.filter(
        forum_name__in=[
            "경기 매칭",
            "용병 모집",
            "팀원 모집",
            "BC 모집",
            "야구 정보",
        ]
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_forum_category'),
    ]

    operations = [
        migrations.RunPython(
            code=bulk_create_forums,
            reverse_code=bulk_delete_forums
        )
    ]
