# Generated by Django 4.2.10 on 2024-02-29 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('cms_code', models.CharField(db_comment='금융결제원코드', max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(db_comment='은행명', max_length=30)),
                ('kor_code', models.CharField(db_comment='한국은행코드', max_length=4, unique=True)),
                ('eng_code', models.CharField(db_comment='영문은행코드', max_length=14, unique=True)),
            ],
            options={
                'verbose_name': '은행',
                'verbose_name_plural': '은행',
                'db_table': 'bank',
            },
        ),
        migrations.CreateModel(
            name='UserBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(db_comment='예금주명', max_length=30)),
                ('account_number', models.CharField(db_comment='계좌번호', max_length=30, unique=True)),
                ('branch_code', models.CharField(db_comment='지점코드', max_length=3, null=True)),
                ('is_verified', models.BooleanField(db_comment='계좌인증여부', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='수정일시')),
                ('user_uuid', models.UUIDField(db_comment='사용자UUID')),
                ('bank', models.ForeignKey(db_comment='은행', on_delete=django.db.models.deletion.PROTECT, to='account.bank')),
            ],
            options={
                'verbose_name': '사용자 은행계좌',
                'verbose_name_plural': '사용자 은행계좌',
                'db_table': 'user_bank_account',
            },
        ),
        migrations.CreateModel(
            name='OwnerBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(db_comment='예금주명', max_length=30)),
                ('account_number', models.CharField(db_comment='계좌번호', max_length=30, unique=True)),
                ('branch_code', models.CharField(db_comment='지점코드', max_length=3, null=True)),
                ('is_verified', models.BooleanField(db_comment='계좌인증여부', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='수정일시')),
                ('facility_uuid', models.UUIDField(db_comment='아카데미UUID')),
                ('bank', models.ForeignKey(db_comment='은행', on_delete=django.db.models.deletion.PROTECT, to='account.bank')),
            ],
            options={
                'verbose_name': '사업자 은행계좌',
                'verbose_name_plural': '사업자 은행계좌',
                'db_table': 'owner_bank_account',
            },
        ),
        migrations.CreateModel(
            name='CoachBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(db_comment='예금주명', max_length=30)),
                ('account_number', models.CharField(db_comment='계좌번호', max_length=30, unique=True)),
                ('branch_code', models.CharField(db_comment='지점코드', max_length=3, null=True)),
                ('is_verified', models.BooleanField(db_comment='계좌인증여부', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='수정일시')),
                ('user_uuid', models.UUIDField(db_comment='사용자UUID')),
                ('coach_uuid', models.UUIDField(db_comment='코치UUID')),
                ('bank', models.ForeignKey(db_comment='은행', on_delete=django.db.models.deletion.PROTECT, to='account.bank')),
            ],
            options={
                'verbose_name': '코치 은행계좌',
                'verbose_name_plural': '코치 은행계좌',
                'db_table': 'coach_bank_account',
            },
        ),
    ]
