# Generated by Django 4.2.8 on 2024-02-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('cms_code', models.CharField(db_comment='금융결제원코드', max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(db_comment='은행명', max_length=30)),
                ('kor_code', models.CharField(db_comment='한국은행코드', max_length=4, unique=True)),
                ('eng_code', models.CharField(db_comment='영문은행코드', max_length=14, unique=True)),
            ],
            options={
                'verbose_name': '은행',
                'verbose_name_plural': '은행',
                'db_table': 'bank',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(db_comment='예금주명', max_length=30)),
                ('account_number', models.CharField(db_comment='계좌번호', max_length=30)),
                ('bank_code', models.CharField(db_comment='은행코드(금융결제원)', max_length=3)),
                ('branch_code', models.CharField(db_comment='지점코드', max_length=3)),
            ],
        ),
    ]
