# Generated by Django 4.2.11 on 2024-03-15 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('cms_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('kor_code', models.CharField(max_length=4, unique=True)),
                ('eng_code', models.CharField(max_length=14, unique=True)),
                ('icon', models.URLField()),
            ],
            options={
                'verbose_name': '은행',
                'verbose_name_plural': '은행',
                'db_table': 'bank',
            },
        ),
        migrations.CreateModel(
            name='UserBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(max_length=30)),
                ('account_number', models.CharField(max_length=30, unique=True)),
                ('branch_code', models.CharField(max_length=3, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_uuid', models.UUIDField()),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.bank')),
            ],
            options={
                'db_table': 'user_bank_account',
            },
        ),
        migrations.CreateModel(
            name='OwnerBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(max_length=30)),
                ('account_number', models.CharField(max_length=30, unique=True)),
                ('branch_code', models.CharField(max_length=3, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility_uuid', models.UUIDField()),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.bank')),
            ],
            options={
                'db_table': 'owner_bank_account',
            },
        ),
        migrations.CreateModel(
            name='CoachBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(max_length=30)),
                ('account_number', models.CharField(max_length=30, unique=True)),
                ('branch_code', models.CharField(max_length=3, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_uuid', models.UUIDField()),
                ('coach_uuid', models.UUIDField()),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.bank')),
            ],
            options={
                'db_table': 'coach_bank_account',
            },
        ),
    ]
