# Generated by Django 4.2.8 on 2024-02-28 01:40

from django.db import migrations

from account.models import Bank

def bulk_create_bank_data(apps, schema_editor):
    Bank.objects.bulk_create(
        objs=[
            Bank(cms_code="002", name="KDB산업은행", kor_code="산업", eng_code="KDB"),
            Bank(cms_code="003", name="IBK기업은행", kor_code="기업", eng_code="IBK"),
            Bank(cms_code="004", name="KB국민은행", kor_code="국민", eng_code="KB"),
            Bank(cms_code="007", name="Sh수협은행", kor_code="수협", eng_code="SH"),
            Bank(cms_code="008", name="수출입은행", kor_code="수출입", eng_code="EXIM"),

            Bank(cms_code="011", name="NH농협은행", kor_code="농협", eng_code="NH"),
            Bank(cms_code="012", name="지역농축협", kor_code="지역농축협", eng_code="LOCAL"),
            Bank(cms_code="020", name="우리은행", kor_code="우리", eng_code="WOORI"),
            Bank(cms_code="023", name="SC제일은행", kor_code="제일", eng_code="SC"),
            Bank(cms_code="027", name="한국씨티은행", kor_code="씨티", eng_code="CITI"),

            Bank(cms_code="031", name="DGB대구은행", kor_code="대구", eng_code="DAEGU"),
            Bank(cms_code="032", name="부산은행", kor_code="부산", eng_code="BUSAN"),
            Bank(cms_code="034", name="광주은행", kor_code="광주", eng_code="GWANGJU"),
            Bank(cms_code="035", name="제주은행", kor_code="제주", eng_code="JEJU"),
            Bank(cms_code="037", name="전북은행", kor_code="전북", eng_code="JEONBUK"),

            Bank(cms_code="039", name="경남은행", kor_code="경남", eng_code="KYONGNAM"),
            Bank(cms_code="045", name="새마을금고", kor_code="새마을", eng_code="SAEMAEUL"),
            Bank(cms_code="048", name="신협중앙회", kor_code="신협", eng_code="SHINHYUP"),
            Bank(cms_code="050", name="상호저축은행", kor_code="상호저축", eng_code="SAVINGBANK"),
            Bank(cms_code="071", name="우체국", kor_code="우체국", eng_code="POST"),

            Bank(cms_code="081", name="KEB하나은행", kor_code="하나", eng_code="KEBHANA"),
            Bank(cms_code="088", name="신한은행", kor_code="신한", eng_code="SHINHAN"),
            Bank(cms_code="089", name="케이뱅크", kor_code="케이뱅크", eng_code="Kbank"),
            Bank(cms_code="090", name="카카오뱅크", kor_code="카카오뱅크", eng_code="KAKAOBANK"),
            Bank(cms_code="092", name="토스뱅크", kor_code="토스뱅크", eng_code="TOSSBANK"),
        ]
    )

def bulk_delete_bank_data(apps, schema_editor):
    Bank.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            code=bulk_create_bank_data,
            reverse_code=bulk_delete_bank_data
        )
    ]
