# Generated by Django 4.2.4 on 2023-11-15 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['date', 'time'], 'verbose_name': '스케줄', 'verbose_name_plural': '스케줄'},
        ),
        migrations.AlterModelTable(
            name='schedule',
            table='schedule',
        ),
    ]
