# Generated by Django 4.2.4 on 2023-11-09 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMember',
            fields=[
                ('user_uuid', models.UUIDField(db_comment='채팅방 멤버', editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(db_comment='채팅방 멤버 이름', max_length=100)),
                ('is_active', models.BooleanField(db_comment='서비스 탈퇴 여부', default=False)),
            ],
            options={
                'db_table': 'chat_member',
                'db_table_comment': '채팅방 멤버',
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='채팅방 이름', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='채팅방 생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='채팅방 수정일')),
                ('room_image', models.ImageField(db_comment='채팅방 이미지', default='chatroom/default.png', upload_to='chatroom/')),
                ('left_members', models.ManyToManyField(blank=True, related_name='left_chatroom', to='chat.chatmember')),
                ('members', models.ManyToManyField(related_name='chatroom', to='chat.chatmember')),
            ],
            options={
                'db_table': 'chatroom',
                'db_table_comment': '채팅방',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.UUIDField(db_comment='채팅 메시지 작성자', editable=False)),
                ('message', models.TextField(db_comment='채팅 메시지', editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='채팅 메시지 작성일')),
                ('deleted', models.BooleanField(db_comment='채팅 메시지 삭제 여부', default=False)),
                ('read', models.BooleanField(db_comment='채팅 메시지 읽음 여부', default=False)),
                ('dialog', models.ForeignKey(db_comment='채팅방', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.chatroom')),
            ],
            options={
                'db_table': 'chat_message',
                'db_table_comment': '채팅 메시지',
            },
        ),
    ]
