# Generated by Django 4.2.4 on 2023-11-07 17:59

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='채팅방 이름', max_length=100)),
                ('description', models.CharField(db_comment='채팅방 설명', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='채팅방 생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='채팅방 수정일')),
                ('members', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), db_comment='채팅방 참여 유저 UUID 리스트', default=list, size=None)),
            ],
            options={
                'db_table': 'chatroom',
                'db_table_comment': '채팅방',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.IntegerField(db_comment='채팅 메시지 작성자')),
                ('message', models.TextField(db_comment='채팅 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='채팅 메시지 작성일')),
                ('read_users', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), db_comment='채팅 메시지 읽은 유저 UUID 리스트', default=list, size=None)),
                ('dialog', models.ForeignKey(db_comment='채팅방', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.chatroom')),
            ],
            options={
                'db_table': 'chat_message',
                'db_table_comment': '채팅 메시지',
            },
        ),
    ]
