# Generated by Django 4.2.4 on 2023-11-04 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='ChatRoom Name. 채팅방 이름', max_length=100)),
                ('description', models.CharField(db_comment='ChatRoom Description. 채팅방 설명', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='ChatRoom Created At. 채팅방 생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='ChatRoom Updated At. 채팅방 수정일')),
            ],
            options={
                'db_table': 'chatroom',
                'db_table_comment': 'ChatRoom. 채팅방',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.IntegerField(db_comment='ChatMessage Author. 채팅 메시지 작성자')),
                ('message', models.TextField(db_comment='ChatMessage. 채팅 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='ChatMessage Created At. 채팅 메시지 작성일')),
                ('dialog', models.ForeignKey(db_comment='ChatRoom. 채팅방', on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom')),
            ],
            options={
                'db_table': 'chat_message',
                'db_table_comment': 'ChatMessage. 채팅 메시지',
            },
        ),
    ]
