# Generated by Django 4.2.4 on 2023-11-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmember',
            name='is_left',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='left_members',
            field=models.ManyToManyField(related_name='left_chatroom', to='chat.chatmember'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='members',
            field=models.ManyToManyField(related_name='chatroom', to='chat.chatmember'),
        ),
    ]
