# Generated by Django 4.2.4 on 2023-11-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chatmember_is_left_chatroom_left_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='left_members',
            field=models.ManyToManyField(blank=True, related_name='left_chatroom', to='chat.chatmember'),
        ),
    ]
