# Generated by Django 4.2.4 on 2023-11-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.UUIDField(db_comment='시설 고유번호')),
                ('user', models.UUIDField(db_comment='사용자 고유번호')),
                ('content', models.TextField(db_comment='내용')),
                ('images', models.JSONField(blank=True, db_comment='이미지 URL 배열', null=True)),
                ('stars', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], db_comment='별점')),
            ],
            options={
                'verbose_name': '시설 리뷰',
                'verbose_name_plural': '시설 리뷰',
                'db_table': 'facility_review',
                'indexes': [models.Index(fields=['facility'], name='facility_review_facility_index'), models.Index(fields=['user'], name='facility_review_user_index')],
            },
        ),
        migrations.CreateModel(
            name='FacilityLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.UUIDField(db_comment='시설 고유번호')),
                ('user', models.UUIDField(db_comment='사용자 고유번호')),
            ],
            options={
                'verbose_name': '시설 좋아요',
                'verbose_name_plural': '시설 좋아요',
                'db_table': 'facility_like',
                'indexes': [models.Index(fields=['facility'], name='facility_like_facility_index'), models.Index(fields=['user'], name='facility_like_user_index')],
            },
        ),
        migrations.CreateModel(
            name='CoachReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach', models.UUIDField(db_comment='코치 고유번호')),
                ('user', models.UUIDField(db_comment='사용자 고유번호')),
                ('content', models.TextField(db_comment='내용')),
                ('content_open', models.BooleanField(db_comment='내용 공개 여부', default=False)),
                ('images', models.JSONField(blank=True, db_comment='이미지 URL 배열', null=True)),
                ('stars', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], db_comment='별점')),
            ],
            options={
                'verbose_name': '레슨 리뷰',
                'verbose_name_plural': '레슨 리뷰',
                'db_table': 'coach_review',
                'indexes': [models.Index(fields=['coach'], name='coach_review_coach_index'), models.Index(fields=['user'], name='coach_review_user_index')],
            },
        ),
        migrations.CreateModel(
            name='CoachLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach', models.UUIDField(db_comment='코치 고유번호')),
                ('user', models.UUIDField(db_comment='사용자 고유번호')),
            ],
            options={
                'verbose_name': '코치 좋아요',
                'verbose_name_plural': '코치 좋아요',
                'db_table': 'coach_like',
                'indexes': [models.Index(fields=['coach'], name='coach_like_coach_index'), models.Index(fields=['user'], name='coach_like_user_index')],
            },
        ),
    ]
