# Generated by Django 4.2.4 on 2023-10-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.UUIDField(db_comment='시설 고유번호')),
                ('reserved_user', models.UUIDField(db_comment='사용자 고유번호')),
                ('start_time', models.DateTimeField(db_comment='시작 시간')),
                ('end_time', models.DateTimeField(db_comment='종료 시간')),
                ('is_confirmed', models.BooleanField(db_comment='예약 승인 여부', default=False)),
            ],
            options={
                'db_table': 'reservation',
            },
        ),
    ]
