# Generated by Django 4.2.4 on 2023-11-15 10:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_comment='상품명', max_length=100)),
                ('description', models.TextField(db_comment='상품 설명')),
                ('price', models.IntegerField(db_comment='가격')),
                ('facility', models.UUIDField(db_comment='시설 고유번호')),
                ('hours', models.IntegerField(db_comment='시간')),
                ('minutes', models.IntegerField(db_comment='분')),
            ],
            options={
                'verbose_name': '예약 상품',
                'verbose_name_plural': '예약 상품',
                'db_table': 'reservation_product',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('uuid', models.UUIDField(db_comment='예약 고유번호', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reserved_user', models.UUIDField(db_comment='사용자 고유번호')),
                ('start_datetime', models.DateTimeField(db_comment='시작 시간')),
                ('end_datetime', models.DateTimeField(db_comment='종료 시간')),
                ('status', models.CharField(choices=[('WA', '대기'), ('CO', '승인'), ('CA', '취소'), ('FI', '완료')], db_comment='예약 상태', default='WA', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='생성일')),
                ('confirmed_at', models.DateTimeField(blank=True, db_comment='승인일', null=True)),
                ('lesson_session', models.ForeignKey(db_comment='레슨 고유번호', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lesson.lessonsession')),
                ('product', models.ForeignKey(db_comment='예약 상품 고유번호', on_delete=django.db.models.deletion.DO_NOTHING, to='reservation.reservationproduct')),
            ],
            options={
                'verbose_name': '예약',
                'verbose_name_plural': '예약',
                'db_table': 'reservation',
                'ordering': ['start_datetime'],
            },
        ),
    ]
