# Generated by Django 4.2.4 on 2023-11-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('WAITING', '대기'), ('CONFIRMED', '승인'), ('CANCELLED', '취소'), ('FINISHED', '완료')], db_comment='예약 상태', default='WAITING', max_length=10),
        ),
    ]
