# Generated by Django 4.2.11 on 2024-03-22 06:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facility', '0003_alter_facilityimage_image'),
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_uuid', models.UUIDField()),
                ('member_name', models.CharField(max_length=10)),
                ('member_phone', models.CharField(max_length=13)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('certification', models.FileField(blank=True, upload_to='')),
                ('baseball_career', models.IntegerField(choices=[(1, '프로 선수 출신'), (2, '대학교 선수 출신'), (3, '고등학교 선수 출신'), (4, '비선수 출신'), (5, '기타')])),
                ('facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facility.facility')),
            ],
            options={
                'db_table': 'coach',
                'unique_together': {('member_uuid', 'uuid')},
            },
        ),
        migrations.CreateModel(
            name='CoachImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(upload_to='')),
                ('cover', models.BooleanField(default=False)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_images', to='coach.coach')),
            ],
            options={
                'db_table': 'coach_image',
            },
        ),
        migrations.CreateModel(
            name='CoachInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField()),
                ('pitching', models.BooleanField(default=False)),
                ('batting', models.BooleanField(default=False)),
                ('defense', models.BooleanField(default=False)),
                ('catching', models.BooleanField(default=False)),
                ('rehabilitation', models.BooleanField(default=False)),
                ('conditioning', models.BooleanField(default=False)),
                ('beginner1', models.BooleanField(default=False)),
                ('beginner2', models.BooleanField(default=False)),
                ('amateur', models.BooleanField(default=False)),
                ('veteran', models.BooleanField(default=False)),
                ('rookie', models.BooleanField(default=False)),
                ('elite', models.BooleanField(default=False)),
                ('individual', models.BooleanField(default=False)),
                ('group', models.BooleanField(default=False)),
                ('team', models.BooleanField(default=False)),
                ('others', models.BooleanField(default=False)),
                ('coach', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_info', to='coach.coach')),
                ('images', models.ManyToManyField(related_name='coach_info', to='coach.coachimage')),
                ('regions', models.ManyToManyField(related_name='coach_info', to='region.sigungu')),
            ],
            options={
                'db_table': 'coach_info',
            },
        ),
    ]
