# Generated by Django 4.2.10 on 2024-03-06 06:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('coach_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_uuid', models.UUIDField(editable=False)),
                ('coach_name', models.CharField(max_length=30)),
                ('coach_phone', models.CharField(max_length=20)),
                ('certification', models.FileField(upload_to='')),
                ('baseball_career', models.IntegerField(choices=[(1, '프로 선수 출신'), (2, '대학교 선수 출신'), (3, '고등학교 선수 출신'), (4, '비선수 출신'), (5, '기타')])),
                ('is_confirmed', models.BooleanField(default=False)),
                ('facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facility.facility')),
            ],
            options={
                'db_table': 'coach',
            },
        ),
        migrations.CreateModel(
            name='CoachInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField()),
                ('pitching', models.BooleanField(default=False)),
                ('batting', models.BooleanField(default=False)),
                ('defense', models.BooleanField(default=False)),
                ('catching', models.BooleanField(default=False)),
                ('rehabilitation', models.BooleanField(default=False)),
                ('conditioning', models.BooleanField(default=False)),
                ('beginner1', models.BooleanField(default=False)),
                ('beginner2', models.BooleanField(default=False)),
                ('amateur', models.BooleanField(default=False)),
                ('veteran', models.BooleanField(default=False)),
                ('rookie', models.BooleanField(default=False)),
                ('elite', models.BooleanField(default=False)),
                ('individual', models.BooleanField(default=False)),
                ('group', models.BooleanField(default=False)),
                ('team', models.BooleanField(default=False)),
                ('others', models.BooleanField(default=False)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coach.coach')),
            ],
            options={
                'db_table': 'coach_info',
            },
        ),
    ]
