# Generated by Django 4.2.11 on 2024-03-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
