# Generated by Django 4.2.11 on 2024-03-22 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coach', '0001_initial'),
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facility.facility'),
        ),
        migrations.AlterUniqueTogether(
            name='coach',
            unique_together={('member_uuid', 'uuid')},
        ),
    ]
