# Generated by Django 4.2.11 on 2024-03-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0001_initial'),
        ('coach', '0003_alter_coach_certification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachinfo',
            name='regions',
            field=models.ManyToManyField(related_name='coach_info', to='region.sigungu'),
        ),
    ]
