# Generated by Django 4.2.11 on 2024-03-22 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0004_coachinfo_regions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='is_complete',
        ),
    ]
