# Generated by Django 4.2.11 on 2024-03-22 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0005_remove_coach_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachinfo',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_info', to='coach.coach'),
        ),
    ]
