# Generated by Django 4.2.8 on 2024-02-16 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sido',
            fields=[
                ('sido_code', models.PositiveBigIntegerField(db_comment='시/도 코드', primary_key=True, serialize=False)),
                ('sido_name', models.CharField(db_comment='시/도 이름', max_length=20)),
            ],
            options={
                'verbose_name': '시/도',
                'verbose_name_plural': '시/도',
                'db_table': 'sido',
            },
        ),
        migrations.CreateModel(
            name='Sigungu',
            fields=[
                ('sigungu_code', models.PositiveBigIntegerField(db_comment='시/군/구 코드', primary_key=True, serialize=False)),
                ('sigungu_name', models.CharField(db_comment='시/군/구 이름', max_length=20)),
                ('sido_code', models.ForeignKey(db_comment='시/도 코드', on_delete=django.db.models.deletion.CASCADE, to='region.sido')),
            ],
            options={
                'verbose_name': '시/군/구',
                'verbose_name_plural': '시/군/구',
                'db_table': 'sigungu',
            },
        ),
    ]
