# Generated by Django 4.2.10 on 2024-02-29 05:47

from django.db import migrations

from region.models import Sido, Sigungu

def insert_initial_data(apps, schema_editor):
    Sido.objects.bulk_create(
        objs=[
            Sido(sido_code=1100000000, sido_name="서울특별시", label="서울"),
            Sido(sido_code=2600000000, sido_name="부산광역시", label="부산"),
            Sido(sido_code=2700000000, sido_name="대구광역시", label="대구"),
            Sido(sido_code=2800000000, sido_name="인천광역시", label="인천"),
            Sido(sido_code=2900000000, sido_name="광주광역시", label="광주"),
            Sido(sido_code=3000000000, sido_name="대전광역시", label="대전"),
            Sido(sido_code=3100000000, sido_name="울산광역시", label="울산"),
            Sido(sido_code=4100000000, sido_name="경기도", label="경기"),
            Sido(sido_code=4300000000, sido_name="충청북도", label="충북"),
            Sido(sido_code=4400000000, sido_name="충청남도", label="충남"),
            Sido(sido_code=4500000000, sido_name="전라북도", label="전북"),
            Sido(sido_code=4600000000, sido_name="전라남도", label="전남"),
            Sido(sido_code=4700000000, sido_name="경상북도", label="경북"),
            Sido(sido_code=4800000000, sido_name="경상남도", label="경남"),
            Sido(sido_code=5000000000, sido_name="제주특별자치도", label="제주"),
            Sido(sido_code=5100000000, sido_name="강원특별자치도", label="강원"),
            Sido(sido_code=3611000000, sido_name="세종특별자치시", label="세종")
        ]
    )

    seoul = Sido.objects.get(sido_code=1100000000)
    busan = Sido.objects.get(sido_code=2600000000)
    daegu = Sido.objects.get(sido_code=2700000000)
    incheon = Sido.objects.get(sido_code=2800000000)
    gwangju = Sido.objects.get(sido_code=2900000000)
    daejeon = Sido.objects.get(sido_code=3000000000)
    ulsan = Sido.objects.get(sido_code=3100000000)
    gyeonggi = Sido.objects.get(sido_code=4100000000)
    chungbuk = Sido.objects.get(sido_code=4300000000)
    chungnam = Sido.objects.get(sido_code=4400000000)
    jeonbuk = Sido.objects.get(sido_code=4500000000)
    jeonnam = Sido.objects.get(sido_code=4600000000)
    gyeongbuk = Sido.objects.get(sido_code=4700000000)
    gyeongnam = Sido.objects.get(sido_code=4800000000)
    jeju = Sido.objects.get(sido_code=5000000000)
    gangwon = Sido.objects.get(sido_code=5100000000)
    sejong = Sido.objects.get(sido_code=3611000000)

    ## 시군구: 서울
    Sigungu.objects.bulk_create(
        objs=[
            Sigungu(sigungu_code=1111000000, sigungu_name="종로구", sido=seoul),
            Sigungu(sigungu_code=1114000000, sigungu_name="중구", sido=seoul),
            Sigungu(sigungu_code=1117000000, sigungu_name="용산구", sido=seoul),
            Sigungu(sigungu_code=1120000000, sigungu_name="성동구", sido=seoul),
            Sigungu(sigungu_code=1121500000, sigungu_name="광진구", sido=seoul),
            Sigungu(sigungu_code=1123000000, sigungu_name="동대문구", sido=seoul),
            Sigungu(sigungu_code=1126000000, sigungu_name="중랑구", sido=seoul),
            Sigungu(sigungu_code=1129000000, sigungu_name="성북구", sido=seoul),
            Sigungu(sigungu_code=1130500000, sigungu_name="강북구", sido=seoul),
            Sigungu(sigungu_code=1132000000, sigungu_name="도봉구", sido=seoul),
            Sigungu(sigungu_code=1135000000, sigungu_name="노원구", sido=seoul),
            Sigungu(sigungu_code=1138000000, sigungu_name="은평구", sido=seoul),
            Sigungu(sigungu_code=1141000000, sigungu_name="서대문구", sido=seoul),
            Sigungu(sigungu_code=1144000000, sigungu_name="마포구", sido=seoul),
            Sigungu(sigungu_code=1147000000, sigungu_name="양천구", sido=seoul),
            Sigungu(sigungu_code=1150000000, sigungu_name="강서구", sido=seoul),
            Sigungu(sigungu_code=1153000000, sigungu_name="구로구", sido=seoul),
            Sigungu(sigungu_code=1154500000, sigungu_name="금천구", sido=seoul),
            Sigungu(sigungu_code=1156000000, sigungu_name="영등포구", sido=seoul),
            Sigungu(sigungu_code=1159000000, sigungu_name="동작구", sido=seoul),
            Sigungu(sigungu_code=1162000000, sigungu_name="관악구", sido=seoul),
            Sigungu(sigungu_code=1165000000, sigungu_name="서초구", sido=seoul),
            Sigungu(sigungu_code=1168000000, sigungu_name="강남구", sido=seoul),
            Sigungu(sigungu_code=1171000000, sigungu_name="송파구", sido=seoul),
            Sigungu(sigungu_code=1174000000, sigungu_name="강동구", sido=seoul)
        ]
    )

    ## 시군구: 부산, 대구
    Sigungu.objects.bulk_create(
        objs=[
            Sigungu(sigungu_code=2611000000, sigungu_name="중구", sido=busan),
            Sigungu(sigungu_code=2614000000, sigungu_name="서구", sido=busan),
            Sigungu(sigungu_code=2617000000, sigungu_name="동구", sido=busan),
            Sigungu(sigungu_code=2620000000, sigungu_name="영도구", sido=busan),
            Sigungu(sigungu_code=2623000000, sigungu_name="부산진구", sido=busan),
            Sigungu(sigungu_code=2626000000, sigungu_name="동래구", sido=busan),
            Sigungu(sigungu_code=2629000000, sigungu_name="남구", sido=busan),
            Sigungu(sigungu_code=2632000000, sigungu_name="북구", sido=busan),
            Sigungu(sigungu_code=2635000000, sigungu_name="해운대구", sido=busan),
            Sigungu(sigungu_code=2638000000, sigungu_name="사하구", sido=busan),
            Sigungu(sigungu_code=2641000000, sigungu_name="금정구", sido=busan),
            Sigungu(sigungu_code=2644000000, sigungu_name="강서구", sido=busan),
            Sigungu(sigungu_code=2647000000, sigungu_name="연제구", sido=busan),
            Sigungu(sigungu_code=2650000000, sigungu_name="수영구", sido=busan),
            Sigungu(sigungu_code=2653000000, sigungu_name="사상구", sido=busan),
            Sigungu(sigungu_code=2671000000, sigungu_name="기장군", sido=busan)
        ] + [
            Sigungu(sigungu_code=2711000000, sigungu_name="중구", sido=daegu),
            Sigungu(sigungu_code=2714000000, sigungu_name="동구", sido=daegu),
            Sigungu(sigungu_code=2717000000, sigungu_name="서구", sido=daegu),
            Sigungu(sigungu_code=2720000000, sigungu_name="남구", sido=daegu),
            Sigungu(sigungu_code=2723000000, sigungu_name="북구", sido=daegu),
            Sigungu(sigungu_code=2726000000, sigungu_name="수성구", sido=daegu),
            Sigungu(sigungu_code=2729000000, sigungu_name="달서구", sido=daegu),
            Sigungu(sigungu_code=2771000000, sigungu_name="달성군", sido=daegu),
            Sigungu(sigungu_code=2772000000, sigungu_name="군위군", sido=daegu)
        ]
    )

    ## 시군구: 인천, 광주, 대전, 울산, 세종
    Sigungu.objects.bulk_create(
        objs=[
            Sigungu(sigungu_code=2811000000, sigungu_name="중구", sido=incheon),
            Sigungu(sigungu_code=2814000000, sigungu_name="동구", sido=incheon),
            Sigungu(sigungu_code=2817700000, sigungu_name="미추홀구", sido=incheon),
            Sigungu(sigungu_code=2818500000, sigungu_name="연수구", sido=incheon),
            Sigungu(sigungu_code=2820000000, sigungu_name="남동구", sido=incheon),
            Sigungu(sigungu_code=2823700000, sigungu_name="부평구", sido=incheon),
            Sigungu(sigungu_code=2824500000, sigungu_name="계양구", sido=incheon),
            Sigungu(sigungu_code=2826000000, sigungu_name="서구", sido=incheon),
            Sigungu(sigungu_code=2871000000, sigungu_name="강화군", sido=incheon),
            Sigungu(sigungu_code=2872000000, sigungu_name="옹진군", sido=incheon)
        ] + [
            Sigungu(sigungu_code=2911000000, sigungu_name="동구", sido=gwangju),
            Sigungu(sigungu_code=2914000000, sigungu_name="서구", sido=gwangju),
            Sigungu(sigungu_code=2915500000, sigungu_name="남구", sido=gwangju),
            Sigungu(sigungu_code=2917000000, sigungu_name="북구", sido=gwangju),
            Sigungu(sigungu_code=2920000000, sigungu_name="광산구", sido=gwangju)
        ] + [
            Sigungu(sigungu_code=3011000000, sigungu_name="동구", sido=daejeon),
            Sigungu(sigungu_code=3014000000, sigungu_name="중구", sido=daejeon),
            Sigungu(sigungu_code=3017000000, sigungu_name="서구", sido=daejeon),
            Sigungu(sigungu_code=3020000000, sigungu_name="유성구", sido=daejeon),
            Sigungu(sigungu_code=3023000000, sigungu_name="대덕구", sido=daejeon)
        ] + [
            Sigungu(sigungu_code=3111000000, sigungu_name="중구", sido=ulsan),
            Sigungu(sigungu_code=3114000000, sigungu_name="남구", sido=ulsan),
            Sigungu(sigungu_code=3117000000, sigungu_name="동구", sido=ulsan),
            Sigungu(sigungu_code=3120000000, sigungu_name="북구", sido=ulsan),
            Sigungu(sigungu_code=3171000000, sigungu_name="울주군", sido=ulsan),
        ] + [
            Sigungu(sigungu_code=3611000000, sigungu_name="세종특별자치시", sido=sejong)
        ]
    )

    ## 시군구: 경기
    Sigungu.objects.bulk_create(
        objs=[
            Sigungu(sigungu_code=4111100000, sigungu_name="수원시 장안구", sido=gyeonggi),
            Sigungu(sigungu_code=4111300000, sigungu_name="수원시 권선구", sido=gyeonggi),
            Sigungu(sigungu_code=4111500000, sigungu_name="수원시 팔달구", sido=gyeonggi),
            Sigungu(sigungu_code=4111700000, sigungu_name="수원시 영통구", sido=gyeonggi),
            Sigungu(sigungu_code=4113100000, sigungu_name="성남시 수정구", sido=gyeonggi),
            Sigungu(sigungu_code=4113300000, sigungu_name="성남시 중원구", sido=gyeonggi),
            Sigungu(sigungu_code=4113500000, sigungu_name="성남시 분당구", sido=gyeonggi),
            Sigungu(sigungu_code=4115000000, sigungu_name="의정부시", sido=gyeonggi),
            Sigungu(sigungu_code=4117100000, sigungu_name="안양시 만안구", sido=gyeonggi),
            Sigungu(sigungu_code=4117300000, sigungu_name="안양시 동안구", sido=gyeonggi),
            Sigungu(sigungu_code=4119000000, sigungu_name="부천시", sido=gyeonggi),
            Sigungu(sigungu_code=4121000000, sigungu_name="광명시", sido=gyeonggi),
            Sigungu(sigungu_code=4122000000, sigungu_name="평택시", sido=gyeonggi),
            Sigungu(sigungu_code=4125000000, sigungu_name="동두천시", sido=gyeonggi),
            Sigungu(sigungu_code=4127100000, sigungu_name="안산시 상록구", sido=gyeonggi),
            Sigungu(sigungu_code=4127300000, sigungu_name="안산시 단원구", sido=gyeonggi),
            Sigungu(sigungu_code=4128100000, sigungu_name="고양시 덕양구", sido=gyeonggi),
            Sigungu(sigungu_code=4128500000, sigungu_name="고양시 일산동구", sido=gyeonggi),
            Sigungu(sigungu_code=4128700000, sigungu_name="고양시 일산서구", sido=gyeonggi),
            Sigungu(sigungu_code=4129000000, sigungu_name="과천시", sido=gyeonggi),
            Sigungu(sigungu_code=4131000000, sigungu_name="구리시", sido=gyeonggi),
            Sigungu(sigungu_code=4136000000, sigungu_name="남양주시", sido=gyeonggi),
            Sigungu(sigungu_code=4137000000, sigungu_name="오산시", sido=gyeonggi),
            Sigungu(sigungu_code=4139000000, sigungu_name="시흥시", sido=gyeonggi),
            Sigungu(sigungu_code=4141000000, sigungu_name="군포시", sido=gyeonggi),
            Sigungu(sigungu_code=4143000000, sigungu_name="의왕시", sido=gyeonggi),
            Sigungu(sigungu_code=4145000000, sigungu_name="하남시", sido=gyeonggi),
            Sigungu(sigungu_code=4146100000, sigungu_name="용인시 처인구", sido=gyeonggi),
            Sigungu(sigungu_code=4146300000, sigungu_name="용인시 기흥구", sido=gyeonggi),
            Sigungu(sigungu_code=4146500000, sigungu_name="용인시 수지구", sido=gyeonggi),
            Sigungu(sigungu_code=4148000000, sigungu_name="파주시", sido=gyeonggi),
            Sigungu(sigungu_code=4150000000, sigungu_name="이천시", sido=gyeonggi),
            Sigungu(sigungu_code=4155000000, sigungu_name="안성시", sido=gyeonggi),
            Sigungu(sigungu_code=4157000000, sigungu_name="김포시", sido=gyeonggi),
            Sigungu(sigungu_code=4159000000, sigungu_name="화성시", sido=gyeonggi),
            Sigungu(sigungu_code=4161000000, sigungu_name="광주시", sido=gyeonggi),
            Sigungu(sigungu_code=4163000000, sigungu_name="양주시", sido=gyeonggi),
            Sigungu(sigungu_code=4165000000, sigungu_name="포천시", sido=gyeonggi),
            Sigungu(sigungu_code=4167000000, sigungu_name="여주시", sido=gyeonggi),
            Sigungu(sigungu_code=4180000000, sigungu_name="연천군", sido=gyeonggi),
            Sigungu(sigungu_code=4182000000, sigungu_name="가평군", sido=gyeonggi),
            Sigungu(sigungu_code=4183000000, sigungu_name="양평군", sido=gyeonggi)
        ]
    )

    ## 시군구: 충청북도, 충청남도
    Sigungu.objects.bulk_create(
        objs=[
            Sigungu(sigungu_code=4311100000, sigungu_name="청주시 상당구", sido=chungbuk),
            Sigungu(sigungu_code=4311200000, sigungu_name="청주시 서원구", sido=chungbuk),
            Sigungu(sigungu_code=4311300000, sigungu_name="청주시 흥덕구", sido=chungbuk),
            Sigungu(sigungu_code=4311400000, sigungu_name="청주시 청원구", sido=chungbuk),
            Sigungu(sigungu_code=4313000000, sigungu_name="충주시", sido=chungbuk),
            Sigungu(sigungu_code=4315000000, sigungu_name="제천시", sido=chungbuk),
            Sigungu(sigungu_code=4372000000, sigungu_name="보은군", sido=chungbuk),
            Sigungu(sigungu_code=4373000000, sigungu_name="옥천군", sido=chungbuk),
            Sigungu(sigungu_code=4374000000, sigungu_name="영동군", sido=chungbuk),
            Sigungu(sigungu_code=4374500000, sigungu_name="증평군", sido=chungbuk),
            Sigungu(sigungu_code=4375000000, sigungu_name="진천군", sido=chungbuk),
            Sigungu(sigungu_code=4376000000, sigungu_name="괴산군", sido=chungbuk),
            Sigungu(sigungu_code=4377000000, sigungu_name="음성군", sido=chungbuk),
            Sigungu(sigungu_code=4380000000, sigungu_name="단양군", sido=chungbuk),
        ] + [
            Sigungu(sigungu_code=4413100000, sigungu_name="천안시 동남구", sido=chungnam),
            Sigungu(sigungu_code=4413300000, sigungu_name="천안시 서북구", sido=chungnam),
            Sigungu(sigungu_code=4415000000, sigungu_name="공주시", sido=chungnam),
            Sigungu(sigungu_code=4418000000, sigungu_name="보령시", sido=chungnam),
            Sigungu(sigungu_code=4420000000, sigungu_name="아산시", sido=chungnam),
            Sigungu(sigungu_code=4421000000, sigungu_name="서산시", sido=chungnam),
            Sigungu(sigungu_code=4423000000, sigungu_name="논산시", sido=chungnam),
            Sigungu(sigungu_code=4425000000, sigungu_name="계룡시", sido=chungnam),
            Sigungu(sigungu_code=4427000000, sigungu_name="당진시", sido=chungnam),
            Sigungu(sigungu_code=4471000000, sigungu_name="금산군", sido=chungnam),
            Sigungu(sigungu_code=4476000000, sigungu_name="부여군", sido=chungnam),
            Sigungu(sigungu_code=4477000000, sigungu_name="서천군", sido=chungnam),
            Sigungu(sigungu_code=4479000000, sigungu_name="청양군", sido=chungnam),
            Sigungu(sigungu_code=4480000000, sigungu_name="홍성군", sido=chungnam),
            Sigungu(sigungu_code=4481000000, sigungu_name="예산군", sido=chungnam),
            Sigungu(sigungu_code=4482500000, sigungu_name="태안군", sido=chungnam)
        ]
    )

    ## 시군구: 전라북도, 전라남도
    Sigungu.objects.bulk_create(
        objs=[
            Sigungu(sigungu_code=4511100000, sigungu_name="전주시 완산구", sido=jeonbuk),
            Sigungu(sigungu_code=4511300000, sigungu_name="전주시 덕진구", sido=jeonbuk),
            Sigungu(sigungu_code=4513000000, sigungu_name="군산시", sido=jeonbuk),
            Sigungu(sigungu_code=4514000000, sigungu_name="익산시", sido=jeonbuk),
            Sigungu(sigungu_code=4518000000, sigungu_name="정읍시", sido=jeonbuk),
            Sigungu(sigungu_code=4519000000, sigungu_name="남원시", sido=jeonbuk),
            Sigungu(sigungu_code=4521000000, sigungu_name="김제시", sido=jeonbuk),
            Sigungu(sigungu_code=4571000000, sigungu_name="완주군", sido=jeonbuk),
            Sigungu(sigungu_code=4572000000, sigungu_name="진안군", sido=jeonbuk),
            Sigungu(sigungu_code=4573000000, sigungu_name="무주군", sido=jeonbuk),
            Sigungu(sigungu_code=4574000000, sigungu_name="장수군", sido=jeonbuk),
            Sigungu(sigungu_code=4575000000, sigungu_name="임실군", sido=jeonbuk),
            Sigungu(sigungu_code=4577000000, sigungu_name="순창군", sido=jeonbuk),
            Sigungu(sigungu_code=4579000000, sigungu_name="고창군", sido=jeonbuk),
            Sigungu(sigungu_code=4580000000, sigungu_name="부안군", sido=jeonbuk),
        ] + [
            Sigungu(sigungu_code=4611000000, sigungu_name="목포시", sido=jeonnam),
            Sigungu(sigungu_code=4613000000, sigungu_name="여수시", sido=jeonnam),
            Sigungu(sigungu_code=4615000000, sigungu_name="순천시", sido=jeonnam),
            Sigungu(sigungu_code=4617000000, sigungu_name="나주시", sido=jeonnam),
            Sigungu(sigungu_code=4623000000, sigungu_name="광양시", sido=jeonnam),
            Sigungu(sigungu_code=4671000000, sigungu_name="담양군", sido=jeonnam),
            Sigungu(sigungu_code=4672000000, sigungu_name="곡성군", sido=jeonnam),
            Sigungu(sigungu_code=4673000000, sigungu_name="구례군", sido=jeonnam),
            Sigungu(sigungu_code=4677000000, sigungu_name="고흥군", sido=jeonnam),
            Sigungu(sigungu_code=4678000000, sigungu_name="보성군", sido=jeonnam),
            Sigungu(sigungu_code=4679000000, sigungu_name="화순군", sido=jeonnam),
            Sigungu(sigungu_code=4680000000, sigungu_name="장흥군", sido=jeonnam),
            Sigungu(sigungu_code=4681000000, sigungu_name="강진군", sido=jeonnam),
            Sigungu(sigungu_code=4682000000, sigungu_name="해남군", sido=jeonnam),
            Sigungu(sigungu_code=4683000000, sigungu_name="영암군", sido=jeonnam),
            Sigungu(sigungu_code=4684000000, sigungu_name="무안군", sido=jeonnam),
            Sigungu(sigungu_code=4686000000, sigungu_name="함평군", sido=jeonnam),
            Sigungu(sigungu_code=4687000000, sigungu_name="영광군", sido=jeonnam),
            Sigungu(sigungu_code=4688000000, sigungu_name="장성군", sido=jeonnam),
            Sigungu(sigungu_code=4689000000, sigungu_name="완도군", sido=jeonnam),
            Sigungu(sigungu_code=4690000000, sigungu_name="진도군", sido=jeonnam),
            Sigungu(sigungu_code=4691000000, sigungu_name="신안군", sido=jeonnam)
        ]
    )

    ## 시군구: 경상북도, 경상남도
    Sigungu.objects.bulk_create(
        objs=[
            Sigungu(sigungu_code=4711100000, sigungu_name="포항시 남구", sido=gyeongbuk),
            Sigungu(sigungu_code=4711300000, sigungu_name="포항시 북구", sido=gyeongbuk),
            Sigungu(sigungu_code=4713000000, sigungu_name="경주시", sido=gyeongbuk),
            Sigungu(sigungu_code=4715000000, sigungu_name="김천시", sido=gyeongbuk),
            Sigungu(sigungu_code=4717000000, sigungu_name="안동시", sido=gyeongbuk),
            Sigungu(sigungu_code=4719000000, sigungu_name="구미시", sido=gyeongbuk),
            Sigungu(sigungu_code=4721000000, sigungu_name="영주시", sido=gyeongbuk),
            Sigungu(sigungu_code=4723000000, sigungu_name="영천시", sido=gyeongbuk),
            Sigungu(sigungu_code=4725000000, sigungu_name="상주시", sido=gyeongbuk),
            Sigungu(sigungu_code=4728000000, sigungu_name="문경시", sido=gyeongbuk),
            Sigungu(sigungu_code=4729000000, sigungu_name="경산시", sido=gyeongbuk),
            Sigungu(sigungu_code=4772000000, sigungu_name="군위군", sido=gyeongbuk),
            Sigungu(sigungu_code=4773000000, sigungu_name="의성군", sido=gyeongbuk),
            Sigungu(sigungu_code=4775000000, sigungu_name="청송군", sido=gyeongbuk),
            Sigungu(sigungu_code=4776000000, sigungu_name="영양군", sido=gyeongbuk),
            Sigungu(sigungu_code=4777000000, sigungu_name="영덕군", sido=gyeongbuk),
            Sigungu(sigungu_code=4782000000, sigungu_name="청도군", sido=gyeongbuk),
            Sigungu(sigungu_code=4783000000, sigungu_name="고령군", sido=gyeongbuk),
            Sigungu(sigungu_code=4784000000, sigungu_name="성주군", sido=gyeongbuk),
            Sigungu(sigungu_code=4785000000, sigungu_name="칠곡군", sido=gyeongbuk),
            Sigungu(sigungu_code=4790000000, sigungu_name="예천군", sido=gyeongbuk),
            Sigungu(sigungu_code=4792000000, sigungu_name="봉화군", sido=gyeongbuk),
            Sigungu(sigungu_code=4793000000, sigungu_name="울진군", sido=gyeongbuk),
            Sigungu(sigungu_code=4794000000, sigungu_name="울릉군", sido=gyeongbuk)
        ] + [
            Sigungu(sigungu_code=4812100000, sigungu_name="창원시 의창구", sido=gyeongnam),
            Sigungu(sigungu_code=4812300000, sigungu_name="창원시 성산구", sido=gyeongnam),
            Sigungu(sigungu_code=4812500000, sigungu_name="창원시 마산합포구", sido=gyeongnam),
            Sigungu(sigungu_code=4812700000, sigungu_name="창원시 마산회원구", sido=gyeongnam),
            Sigungu(sigungu_code=4812900000, sigungu_name="창원시 진해구", sido=gyeongnam),
            Sigungu(sigungu_code=4817000000, sigungu_name="진주시", sido=gyeongnam),
            Sigungu(sigungu_code=4822000000, sigungu_name="통영시", sido=gyeongnam),
            Sigungu(sigungu_code=4824000000, sigungu_name="사천시", sido=gyeongnam),
            Sigungu(sigungu_code=4825000000, sigungu_name="김해시", sido=gyeongnam),
            Sigungu(sigungu_code=4827000000, sigungu_name="밀양시", sido=gyeongnam),
            Sigungu(sigungu_code=4831000000, sigungu_name="거제시", sido=gyeongnam),
            Sigungu(sigungu_code=4833000000, sigungu_name="양산시", sido=gyeongnam),
            Sigungu(sigungu_code=4872000000, sigungu_name="의령군", sido=gyeongnam),
            Sigungu(sigungu_code=4873000000, sigungu_name="함안군", sido=gyeongnam),
            Sigungu(sigungu_code=4874000000, sigungu_name="창녕군", sido=gyeongnam),
            Sigungu(sigungu_code=4882000000, sigungu_name="고성군", sido=gyeongnam),
            Sigungu(sigungu_code=4884000000, sigungu_name="남해군", sido=gyeongnam),
            Sigungu(sigungu_code=4885000000, sigungu_name="하동군", sido=gyeongnam),
            Sigungu(sigungu_code=4886000000, sigungu_name="산청군", sido=gyeongnam),
            Sigungu(sigungu_code=4887000000, sigungu_name="함양군", sido=gyeongnam),
            Sigungu(sigungu_code=4888000000, sigungu_name="거창군", sido=gyeongnam),
            Sigungu(sigungu_code=4889000000, sigungu_name="합천군", sido=gyeongnam)
        ]
    )

    ## 시군구: 제주, 강원
    Sigungu.objects.bulk_create(
        objs=[
            Sigungu(sigungu_code=5011000000, sigungu_name="제주시", sido=jeju),
            Sigungu(sigungu_code=5013000000, sigungu_name="서귀포시", sido=jeju)
        ] + [
            Sigungu(sigungu_code=5111000000, sigungu_name="춘천시", sido=gangwon),
            Sigungu(sigungu_code=5113000000, sigungu_name="원주시", sido=gangwon),
            Sigungu(sigungu_code=5115000000, sigungu_name="강릉시", sido=gangwon),
            Sigungu(sigungu_code=5117000000, sigungu_name="동해시", sido=gangwon),
            Sigungu(sigungu_code=5119000000, sigungu_name="태백시", sido=gangwon),
            Sigungu(sigungu_code=5121000000, sigungu_name="속초시", sido=gangwon),
            Sigungu(sigungu_code=5123000000, sigungu_name="삼척시", sido=gangwon),
            Sigungu(sigungu_code=5172000000, sigungu_name="홍천군", sido=gangwon),
            Sigungu(sigungu_code=5173000000, sigungu_name="횡성군", sido=gangwon),
            Sigungu(sigungu_code=5175000000, sigungu_name="영월군", sido=gangwon),
            Sigungu(sigungu_code=5176000000, sigungu_name="평창군", sido=gangwon),
            Sigungu(sigungu_code=5177000000, sigungu_name="정선군", sido=gangwon),
            Sigungu(sigungu_code=5178000000, sigungu_name="철원군", sido=gangwon),
            Sigungu(sigungu_code=5179000000, sigungu_name="화천군", sido=gangwon),
            Sigungu(sigungu_code=5180000000, sigungu_name="양구군", sido=gangwon),
            Sigungu(sigungu_code=5181000000, sigungu_name="인제군", sido=gangwon),
            Sigungu(sigungu_code=5182000000, sigungu_name="고성군", sido=gangwon),
            Sigungu(sigungu_code=5183000000, sigungu_name="양양군", sido=gangwon)
        ]
    )

def delete_initial_data(apps, schema_editor):
    Sido.objects.all().delete()
    Sigungu.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            code=insert_initial_data,
            reverse_code=delete_initial_data
        )
    ]
