# Generated by Django 4.2.10 on 2024-02-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sido',
            name='label',
            field=models.CharField(db_comment='라벨', default='', max_length=2),
            preserve_default=False,
        ),
    ]
