# Generated by Django 4.2.10 on 2024-02-29 01:22

from django.db import migrations

from region.models import Sido

def add_labels(apps, schema_editor):
    seoul = Sido.objects.get(sido_name="서울특별시")
    seoul.label = "서울"
    seoul.save()

    busan = Sido.objects.get(sido_name="부산광역시")
    busan.label = "부산"
    busan.save()

    daegu = Sido.objects.get(sido_name="대구광역시")
    daegu.label = "대구"
    daegu.save()

    incheon = Sido.objects.get(sido_name="인천광역시")
    incheon.label = "인천"
    incheon.save()

    gwangju = Sido.objects.get(sido_name="광주광역시")
    gwangju.label = "광주"
    gwangju.save()

    daejeon = Sido.objects.get(sido_name="대전광역시")
    daejeon.label = "대전"
    daejeon.save()

    ulsan = Sido.objects.get(sido_name="울산광역시")
    ulsan.label = "울산"
    ulsan.save()

    gyunggi = Sido.objects.get(sido_name="경기도")
    gyunggi.label = "경기"
    gyunggi.save()

    chungbuk = Sido.objects.get(sido_name="충청북도")
    chungbuk.label = "충북"
    chungbuk.save()

    chungnam = Sido.objects.get(sido_name="충청남도")
    chungnam.label = "충남"
    chungnam.save()

    jeonbuk = Sido.objects.get(sido_name="전라북도")
    jeonbuk.label = "전북"
    jeonbuk.save()

    jeonnam = Sido.objects.get(sido_name="전라남도")
    jeonnam.label = "전남"
    jeonnam.save()

    gyeongbuk = Sido.objects.get(sido_name="경상북도")
    gyeongbuk.label = "경북"
    gyeongbuk.save()

    gyeongnam = Sido.objects.get(sido_name="경상남도")
    gyeongnam.label = "경남"
    gyeongnam.save()

    jeju = Sido.objects.get(sido_name="제주특별자치도")
    jeju.label = "제주"
    jeju.save()

    gangwon = Sido.objects.get(sido_name="강원특별자치도")
    gangwon.label = "강원"
    gangwon.save()

    sejong = Sido.objects.get(sido_name="세종특별자치시")
    sejong.label = "세종"
    sejong.save()

def remove_labels(apps, schema_editor):
    Sido.objects.update(label="")

class Migration(migrations.Migration):

    dependencies = [
        ('region', '0003_sido_label'),
    ]

    operations = [
        migrations.RunPython(code=add_labels, reverse_code=remove_labels),
    ]
