# Generated by Django 4.2.10 on 2024-02-19 08:26

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('region', '0002_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('uuid', models.UUIDField(db_comment='시설 고유번호', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_comment='시설 이름', max_length=30)),
                ('owner_uuid', models.UUIDField(db_comment='시설 소유자 유저번호')),
                ('owner_name', models.CharField(db_comment='시설 소유자 이름', max_length=30)),
                ('owner_phone', models.CharField(db_comment='시설 소유자 전화번호', max_length=20)),
                ('reg_code', models.CharField(db_comment='시설 사업자 등록번호', max_length=20, unique=True)),
                ('phone', models.CharField(db_comment='시설 전화번호', max_length=20)),
                ('road_address_part1', models.CharField(db_comment='도로명 주소 (행정구역)', max_length=255)),
                ('road_address_part2', models.CharField(db_comment='도로명 주소 (상세영역)', max_length=255)),
                ('building_name', models.CharField(db_comment='건물 이름', max_length=255)),
                ('eng_address', models.CharField(db_comment='영문 주소', max_length=255)),
                ('jibun_address', models.CharField(db_comment='지번 주소', max_length=255)),
                ('zip_code', models.CharField(db_comment='우편번호', max_length=10)),
                ('longitude', models.FloatField(db_comment='Longitude. 경도')),
                ('latitude', models.FloatField(db_comment='Latitude. 위도')),
                ('is_confirmed', models.BooleanField(db_comment='시설 승인 여부', default=False)),
                ('region', models.ForeignKey(db_comment='시설 시군구', on_delete=django.db.models.deletion.PROTECT, to='region.sigungu')),
            ],
            options={
                'verbose_name': '시설',
                'verbose_name_plural': '시설',
                'db_table': 'facility',
            },
        ),
        migrations.CreateModel(
            name='FacilityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField(db_comment='시설 소개글')),
                ('weekday_open', models.TimeField(db_comment='평일 오픈 시간')),
                ('weekday_close', models.TimeField(db_comment='평일 마감 시간')),
                ('saturday_open', models.TimeField(db_comment='토요일 오픈 시간')),
                ('saturday_close', models.TimeField(db_comment='토요일 마감 시간')),
                ('sunday_open', models.TimeField(db_comment='일요일 오픈 시간')),
                ('sunday_close', models.TimeField(db_comment='일요일 마감 시간')),
                ('wifi', models.BooleanField(db_comment='와이파이', default=False)),
                ('water', models.BooleanField(db_comment='정수기', default=False)),
                ('free_parking', models.BooleanField(db_comment='무료 주차', default=False)),
                ('paid_parking', models.BooleanField(db_comment='유료 주차', default=False)),
                ('resting_area', models.BooleanField(db_comment='휴게공간', default=False)),
                ('separate_toilet', models.BooleanField(db_comment='남녀 화장실 구분', default=False)),
                ('air_conditioner', models.BooleanField(db_comment='에어컨', default=False)),
                ('heating', models.BooleanField(db_comment='난방', default=False)),
                ('locker', models.BooleanField(db_comment='사물함', default=False)),
                ('changing_room', models.BooleanField(db_comment='탈의실', default=False)),
                ('shower', models.BooleanField(db_comment='샤워', default=False)),
                ('sauna', models.BooleanField(db_comment='사우나', default=False)),
                ('no_smoking', models.BooleanField(db_comment='금연구역', default=False)),
                ('smoking_room', models.BooleanField(db_comment='흡연실', default=False)),
                ('kids_room', models.BooleanField(db_comment='키즈룸', default=False)),
                ('no_kids', models.BooleanField(db_comment='노키즈존', default=False)),
                ('num_mounds', models.PositiveIntegerField(db_comment='마운드 수')),
                ('num_plates', models.PositiveIntegerField(db_comment='타석 수')),
                ('wood_bats', models.BooleanField(db_comment='목재배트', default=False)),
                ('aluminium_bats', models.BooleanField(db_comment='알루미늄배트', default=False)),
                ('glove', models.BooleanField(db_comment='글러브', default=False)),
                ('catcher_gear', models.BooleanField(db_comment='캐쳐장비', default=False)),
                ('pitching_machine', models.BooleanField(db_comment='피칭머신', default=False)),
                ('batting_tee', models.BooleanField(db_comment='배팅티', default=False)),
                ('helmets', models.BooleanField(db_comment='헬멧', default=False)),
                ('speed_gun', models.BooleanField(db_comment='스피드건', default=False)),
                ('video_analysis', models.BooleanField(db_comment='영상분석', default=False)),
                ('monitor', models.BooleanField(db_comment='모니터', default=False)),
                ('speaker', models.BooleanField(db_comment='스피커', default=False)),
                ('fitness', models.BooleanField(db_comment='피트니스', default=False)),
                ('vending_machine', models.BooleanField(db_comment='자판기', default=False)),
                ('proshop', models.BooleanField(db_comment='프로샵', default=False)),
                ('group_lesson', models.BooleanField(db_comment='그룹레슨', default=False)),
                ('private_lesson', models.BooleanField(db_comment='개인레슨', default=False)),
                ('cleats_allowed', models.BooleanField(db_comment='스파이크 허용', default=False)),
                ('outdoor', models.BooleanField(db_comment='야외시설', default=False)),
                ('pets_allowed', models.BooleanField(db_comment='애완동물 허용', default=False)),
                ('wheelchair', models.BooleanField(db_comment='휠체어', default=False)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='facility_images'), blank=True, db_comment='시설 이미지', null=True, size=None)),
                ('facility', models.ForeignKey(db_comment='시설 고유번호', on_delete=django.db.models.deletion.CASCADE, to='facility.facility')),
            ],
            options={
                'verbose_name': '시설 정보',
                'verbose_name_plural': '시설 정보',
                'db_table': 'facility_info',
            },
        ),
    ]
