# Generated by Django 4.2.8 on 2024-01-31 03:37

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='coaches',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='description',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='hashtags',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='image_urls',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='intro',
        ),
        migrations.AddField(
            model_name='facility',
            name='owner_name',
            field=models.CharField(db_comment='시설 소유자 이름', default='a', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facility',
            name='owner_phone',
            field=models.CharField(db_comment='시설 소유자 전화번호', default="000000", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facility',
            name='address',
            field=models.ForeignKey(db_comment='시설 주소', on_delete=django.db.models.deletion.PROTECT, to='facility.address'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(db_comment='시설 이름', max_length=30),
        ),
        migrations.CreateModel(
            name='FacilityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_urls', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), db_comment='시설 이미지 URL', size=None)),
                ('hashtags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), db_comment='시설 해시태그', size=None)),
                ('coaches', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), db_comment='시설 코치 고유번호 배열', size=None)),
                ('intro', models.TextField(db_comment='시설 소개글')),
                ('description', models.TextField(db_comment='시설 설명')),
                ('facility', models.ForeignKey(db_comment='시설 고유번호', on_delete=django.db.models.deletion.CASCADE, to='facility.facility')),
            ],
            options={
                'verbose_name': '시설 정보',
                'verbose_name_plural': '시설 정보',
                'db_table': 'facility_info',
            },
        ),
    ]
