# Generated by Django 4.2.11 on 2024-03-22 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'custom_equipment',
            },
        ),
        migrations.AddField(
            model_name='facilityinfo',
            name='images',
            field=models.ManyToManyField(related_name='facility_info', to='facility.facilityimage'),
        ),
        migrations.AlterField(
            model_name='facilityinfo',
            name='facility',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facility_info', to='facility.facility'),
        ),
        migrations.AddField(
            model_name='facilityinfo',
            name='custom_equipment',
            field=models.ManyToManyField(related_name='facility_info', to='facility.customequipment'),
        ),
    ]
