# Generated by Django 4.2.11 on 2024-03-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0002_facility_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityimage',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
