# Generated by Django 4.2.8 on 2024-01-31 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0002_remove_facility_coaches_remove_facility_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='reg_code',
            field=models.CharField(db_comment='시설 사업자 등록번호', default='000000', max_length=20),
            preserve_default=False,
        ),
    ]
