# Generated by Django 4.2.4 on 2023-10-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='owner_uuid',
            field=models.UUIDField(db_comment='시설 소유자 유저번호'),
        ),
        migrations.CreateModel(
            name='FacilityReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.UUIDField(db_comment='시설 고유번호')),
                ('user', models.UUIDField(db_comment='사용자 고유번호')),
                ('content', models.TextField(db_comment='내용')),
                ('images', models.JSONField(blank=True, db_comment='이미지 URL 배열', null=True)),
                ('stars', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], db_comment='별점')),
            ],
            options={
                'db_table': 'review',
                'indexes': [models.Index(fields=['facility'], name='facility_review_facility_index'), models.Index(fields=['user'], name='facility_review_user_index')],
            },
        ),
        migrations.CreateModel(
            name='FacilityLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.UUIDField(db_comment='시설 고유번호')),
                ('user', models.UUIDField(db_comment='사용자 고유번호')),
            ],
            options={
                'db_table': 'like',
                'indexes': [models.Index(fields=['facility'], name='facility_like_facility_index'), models.Index(fields=['user'], name='facility_like_user_index')],
            },
        ),
    ]
