# Generated by Django 4.2.4 on 2023-10-26 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='coach', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('academic_background', models.TextField(db_comment='학력', help_text='학력을 입력해주세요.')),
                ('baseball_career', models.TextField(db_comment='야구 경력', help_text='야구 경력을 입력해주세요.')),
                ('coaching_career', models.TextField(db_comment='코칭 경력', help_text='코칭 경력을 입력해주세요.')),
            ],
            options={
                'verbose_name': 'coach',
                'verbose_name_plural': 'coaches',
                'db_table': 'coach',
            },
        ),
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='counselor', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'counselor',
                'verbose_name_plural': 'counselors',
                'db_table': 'counselor',
            },
            bases=('user.customuser',),
        ),
        migrations.CreateModel(
            name='FacilityOwner',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='facility_owner', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('facility_name', models.CharField(db_comment='시설명', max_length=150)),
                ('facility_address', models.CharField(db_comment='시설 주소', max_length=150)),
                ('facility_phone_number', phonenumber_field.modelfields.PhoneNumberField(db_comment='시설 전화번호', max_length=128, region=None)),
            ],
            options={
                'verbose_name': 'facility_owner',
                'verbose_name_plural': 'facility_owners',
                'db_table': 'facility_owner',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='partner', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'partner',
                'verbose_name_plural': 'partners',
                'db_table': 'partner',
            },
        ),
    ]
