# Generated by Django 4.2.9 on 2024-01-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_is_facility_owner_delete_facilityowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_deleted',
            field=models.BooleanField(db_comment='계정 삭제 여부', default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(db_comment='계정 활성화 여부 (본인인증)', default=False, help_text='Designates whether this user should be treated as active.'),
        ),
    ]
