# Generated by Django 4.2.4 on 2023-10-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_coach_counselor_facilityowner_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, db_comment='닉네임', max_length=150, null=True),
        ),
    ]
