# Generated by Django 4.2.9 on 2024-01-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_is_deleted_alter_customuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(db_comment='전화번호 인증 여부', default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(db_comment='계정 활성화 여부', default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.'),
        ),
    ]
