# Generated by Django 4.2.4 on 2023-11-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='is_approved',
            field=models.BooleanField(db_comment='코치 승인 여부', default=False),
        ),
    ]
