name: Coveralls

on:
  pull_request:
    branches: [ "dev" ]
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      USER_MANAGEMENT_SECRET_KEY: ${{ secrets.USER_MANAGEMENT_SECRET_KEY }}
      PAYMENTS_SECRET_KEY: ${{ secrets.PAYMENTS_SECRET_KEY }}
      PRODUCTS_SECRET_KEY: ${{ secrets.PRODUCTS_SECRET_KEY }}
      COMMUNITY_SECRET_KEY: ${{ secrets.COMMUNITY_SECRET_KEY }}
      CALENDAR_SECRET_KEY: ${{ secrets.CALENDAR_SECRET_KEY }}
      API_GATEWAY_SECRET_KEY: ${{ secrets.API_GATEWAY_SECRET_KEY }}
      PRODUCTS_DB_PASSWORD: ${{ secrets.PRODUCTS_DB_PASSWORD }}
      PRODUCTS_DB_USER: ${{ secrets.PRODUCTS_DB_USER }}
      PRODUCTS_DB_NAME: ${{ secrets.PRODUCTS_DB_NAME }}
      COMMUNITY_DB_PASSWORD: ${{ secrets.COMMUNITY_DB_PASSWORD }}
      COMMUNITY_DB_USER: ${{ secrets.COMMUNITY_DB_USER }}
      COMMUNITY_DB_NAME: ${{ secrets.COMMUNITY_DB_NAME }}
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
    services:
      postgres_products:
        image: postgres:14
        env:
          POSTGRES_USER: ${{ secrets.PRODUCTS_DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.PRODUCTS_DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.PRODUCTS_DB_NAME }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      postgres_community:
        image: postgres:14
        env:
          POSTGRES_USER: ${{ secrets.COMMUNITY_DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.COMMUNITY_DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.COMMUNITY_DB_NAME }}
        ports:
          - 5433:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install graphviz graphviz-dev
        sudo apt-get install lcov
        pip install -r requirements.txt

    - name: Setup Django Database Config
      run: |
        echo "DATABASE_URL=postgres://${{ secrets.PRODUCTS_DB_USER }}:${{ secrets.PRODUCTS_DB_PASSWORD }}@postgres:5432/${{ secrets.PRODUCTS_DB_NAME }}" >> .env
        echo "DATABASE_URL=postgres://${{ secrets.COMMUNITY_DB_USER }}:${{ secrets.COMMUNITY_DB_PASSWORD }}@postgres:5432/${{ secrets.COMMUNITY_DB_NAME }}" >> .env

    - name: Run user_management tests
      run: |
        cd user_management_service
        coverage run --source='.' manage.py test
        coverage lcov -o user_management_coverage.lcov
        cd ..

    - name: Run products tests
      run: |
        cd products_service
        coverage run --source='.' manage.py test
        coverage lcov -o products_coverage.lcov
        cd ..

    - name: Run community tests
      run: |
        cd community_service
        coverage run --source='.' manage.py test
        coverage lcov -o community_coverage.lcov
        cd ..

    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v2.2.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        files: user_management_service/user_management_coverage.lcov products_service/products_coverage.lcov community_service/community_coverage.lcov
        flag-name: community_service
