name: Django Backend Test

on:
  push:
    branches: [ "main", "dev", "staging" ]
  pull_request:
    branches: [ "main", "dev", "staging" ]
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      USER_MANAGEMENT_SECRET_KEY: ${{ secrets.USER_MANAGEMENT_SECRET_KEY }}
      RESERVATIONS_SECRET_KEY: ${{ secrets.RESERVATIONS_SECRET_KEY }}
      RESERVATIONS_DB_PASSWORD: ${{ secrets.RESERVATIONS_DB_PASSWORD }}
      RESERVATIONS_DB_USER: ${{ secrets.RESERVATIONS_DB_USER }}
      RESERVATIONS_DB_NAME: ${{ secrets.RESERVATIONS_DB_NAME }}
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: ${{ secrets.RESERVATIONS_DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.RESERVATIONS_DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.RESERVATIONS_DB_NAME }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install graphviz graphviz-dev
        pip install -r requirements.txt

    - name: Setup Django Database Config
      run: |
        echo "DATABASE_URL=postgres://${{ secrets.RESERVATIONS_DB_USER }}:${{ secrets.RESERVATIONS_DB_PASSWORD }}@postgres:5432/${{ secrets.RESERVATIONS_DB_NAME }}" >> .env

    - name: Run User Management Tests
      run: |
        cd user_management_service
        python manage.py test

    - name: Run Reservations Tests
      run: |
        cd reservations_service
        python manage.py test

    - name: Run Community Tests
      run: |
        cd community_service
        python manage.py test
