name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      USER_MANAGEMENT_SECRET_KEY: ${{ secrets.USER_MANAGEMENT_SECRET_KEY }}
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m venv test
        apt-get install graphviz graphviz-dev
        source test/bin/activate
        pip install -r requirements.txt
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        source test/bin/activate
        DJANGO_SETTINGS_MODULE=community_service.settings pylint **/*.py --load-plugins pylint_django
        DJANGO_SETTINGS_MODULE=file_management_service.settings pylint **/*.py --load-plugins pylint_django
        DJANGO_SETTINGS_MODULE=payments_service.settings pylint **/*.py --load-plugins pylint_django
        DJANGO_SETTINGS_MODULE=reservations_service.settings pylint **/*.py --load-plugins pylint_django
        DJANGO_SETTINGS_MODULE=user_management_service.settings pylint **/*.py --load-plugins pylint_django
        pylint $(git ls-files '*.py')
