name: Auto Create PR to UserTest

on:
  push:
    branches:
      - dev

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "dev"
          destination_branch: "usertest"
          pr_title: "Auto Create PR to UserTest"
          pr_body: "Auto Create PR to UserTest"
          github_token: ${{ secrets.GITHUB_TOKEN }}
