name: Auto Create PR to UserTest

on:
  push:
    branches:
      - dev

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: "usertest"
          title: "Auto Create PR to UserTest"
          body: "Auto Create PR to UserTest"
